<div class="row">
  <div class="col-md-12">
    <h1>EHRServer Community</h1>
    <p>Tools, sample code, resources, and community support.</p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Clients &amp; Helpers for different languages</h2>
    <ol>
     <li>
       <a href="https://github.com/ppazos/EHRClientPHP" target="_blank">PHP</a>
     </li>
     <li>
       <a href="https://github.com/ppazos/cabolabs-ehrserver-js" target="_blank">Javascript</a>
     </li>
     <li>
       <a href="https://github.com/ppazos/cabolabs-ehrserver-groovy" target="_blank">Groovy</a>
     </li>
     <li>
       <a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/api/ehrserver_rest_insomnia.json" target="_blank">Insomnia REST Client Test Requests</a>
     </li>
     <li>
       <a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/api/swagger.yaml" target="_blank">Swagger API Specification (Beta)</a>
     </li>
     <li>
       <a href="https://swaggerhub.com/apis/ppazos/ehr-server/0.9.5" target="_blank">Swagger API Test (Beta)</a>
     </li>
     <li>
       More soon!
     </li>
     <li>
       <a href="<?=$_base_dir?>/contact">Let us know</a> if you created a client for other languages!
     </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Sample applications that use the EHRServer as backend</h2>
    <ol>
     <li>
       <a href="https://github.com/ppazos/cabolabs-emrapp" target="_blank">EMRApp</a>
       : Sample EMR application that uses the EHRServer as backend
     </li>
     <li>
       <a href="https://github.com/ppazos/EHRCommitter" target="_blank">EHRCommitter</a>
       : testing application that generates forms based on OPTs to commit data to the EHRServer
     </li>
     <li>
       <a href="https://github.com/ppazos/notes" target="_blank">Notes</a>
       : web app to keep your psycotheray notes organized, uses the EHRServer as a secondary storage / backup
     </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Tools</h2>
    <ol>
     <li>
       <a href="https://github.com/ppazos/openEHR-OPT" target="_blank">openEHR-OPT</a>
       : command line tools to work with openEHR Operational Templates
     </li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Are you using the EHRServer?</h2>
    <a href="<?=$_base_dir?>/contact">Let us know!</a>. We are delighted to know that you are currently using it in your projects, and we
    can help you getting onboard and disseminate your work in the community.
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <h2>Sample clinical documents</h2>
    <p>Here you can find a list of sample clinical document definitions (openEHR Operational Templates), with correspondent sample instances.
    The instances contain random/autogenerated data, and is not clinical correct. The goal of these resources is to provide technical examples
    about the structure used to commit and retrieve data when using the EHRServer.</p>
    
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Encounter</h3>
      </div>
      <div class="panel-body">
        <p>Template ID: <a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/opts/production/simple_encounter_not_coded_diagnosis/simple_encounter_en.v1.opt" target="_blank">simple_encounter_en.v1</a></p>
        <p>openEHR Archetypes Referenced:
           <ul>
             <li>openEHR-EHR-COMPOSITION.encounter.v1</li>
             <li>openEHR-EHR-EVALUATION.reason_for_encounter.v1</li>
             <li>openEHR-EHR-SECTION.vital_signs.v0</li>
             <li>openEHR-EHR-OBSERVATION.pulse.v1</li>
             <li>openEHR-EHR-OBSERVATION.height.v1</li>
             <li>openEHR-EHR-OBSERVATION.body_weight.v1</li>
             <li>openEHR-EHR-OBSERVATION.respiration.v1</li>
             <li>openEHR-EHR-OBSERVATION.body_temperature.v2.adl</li>
             <li>openEHR-EHR-OBSERVATION.blood_pressure.v1</li>
             <li>openEHR-EHR-OBSERVATION.indirect_oximetry.v0</li>
             <li>openEHR-EHR-OBSERVATION.exam.v1</li>
             <li>openEHR-EHR-EVALUATION.problem_diagnosis.v1</li>
           </ul>
        </p>
        <p><a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/opts/production/simple_encounter_not_coded_diagnosis/simple_encounter_en.v1_20170728025738_1.xml" target="_blank">Sample instance</a></p>
      </div>
      <div class="panel-footer">v1, English</div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Vital Signs Summary</h3>
      </div>
      <div class="panel-body">
        <p>Template ID: <a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/opts/production/vital_signs/Vital_Signs_Summary.EN.v1.opt" target="_blank">Vital_Signs_Summary.EN.v1</a></p>
        <p>openEHR Archetypes Referenced:
           <ul>
             <li>openEHR-EHR-COMPOSITION.health_summary.v1</li>
             <li>openEHR-EHR-SECTION.vital_signs.v0</li>
             <li>openEHR-EHR-OBSERVATION.pulse.v1</li>
             <li>openEHR-EHR-OBSERVATION.height.v1</li>
             <li>openEHR-EHR-OBSERVATION.body_weight.v1</li>
             <li>openEHR-EHR-OBSERVATION.respiration.v1</li>
             <li>openEHR-EHR-OBSERVATION.body_temperature.v2.adl</li>
             <li>openEHR-EHR-OBSERVATION.blood_pressure.v1</li>
             <li>openEHR-EHR-OBSERVATION.indirect_oximetry.v0</li>
           </ul>
        </p>
        <p><a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/opts/production/vital_signs/Vital_Signs_Summary.EN.v1_20170728024935_1.xml" target="_blank">Sample instance</a></p>
      </div>
      <div class="panel-footer">v1, English</div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Psychotherapy Note</h3>
      </div>
      <div class="panel-body">
        <p>Template ID: <a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/opts/production/psychotherapy_note/Psychotherapy_Note.EN.v1.opt" target="_blank">Psychotherapy_Note.EN.v1</a></p>
        <p>openEHR Archetypes Referenced:
           <ul>
             <li>openEHR-EHR-COMPOSITION.health_summary-categorized.v1.adl</li>
             <li>openEHR-EHR-EVALUATION.clinical_synopsis.v1.adl</li>
           </ul>
        </p>
        <p><a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/opts/production/psychotherapy_note/Psychotherapy_Note.EN.v1_20170724075238_1.xml" target="_blank">Sample instance</a></p>
      </div>
      <div class="panel-footer">v1, English</div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-primary">
         <div class="panel-heading">
           <h3 class="panel-title">OPT Validator</h3>
         </div>
         <div class="panel-body">
           <p>Use this XSD to validate instances of openEHR Operational Templates. When loading OPTs into the EHRServer, the OPT format is validated.</p>
           <p><a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/xsd/OperationalTemplate.xsd" target="_blank">OperationalTemplate.xsd</a></p>
         </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-primary">
         <div class="panel-heading">
           <h3 class="panel-title">Clinical Document Validator</h3>
         </div>
         <div class="panel-body">
           <p>Use this XSD to validate clinical document instances. This follows the openEHR clinical document structure with versioning information.</p>
           <p><a href="https://github.com/ppazos/cabolabs-ehrserver/blob/master/xsd/Version.xsd" target="_blank">Version.xsd</a></p>
         </div>
        </div>
      </div>
    </div>
    
  </div>
</div>
