<style type="text/css">
/*Vertical Sliding*/
h1 div {
   display: inline;
}
h1 div#main_text_2 {
   margin-left: 2.215em;
}
.slidingVertical{
	display: inline;
	/*text-indent: 8px;*/
}
.slidingVertical span{
	animation: topToBottom 10.0s linear infinite 0s;
	-ms-animation: topToBottom 10.0s linear infinite 0s;
	-webkit-animation: topToBottom 10.0s linear infinite 0s;
	color: #00abe9;
	opacity: 0;
	overflow: hidden;
	position: absolute;
}
.slidingVertical span:nth-child(2){
	animation-delay: 2.5s;
	-ms-animation-delay: 2.5s;
	-webkit-animation-delay: 2.5s;
}
.slidingVertical span:nth-child(3){
	animation-delay: 5s;
	-ms-animation-delay: 5s;
	-webkit-animation-delay: 5s;
}
.slidingVertical span:nth-child(4){
	animation-delay: 7.5s;
	-ms-animation-delay: 7.5s;
	-webkit-animation-delay: 7.5s;
}


/*topToBottom Animation*/
@-moz-keyframes topToBottom{
	0% { opacity: 0; }
	5% { opacity: 0; -moz-transform: translateY(-50px); }
	10% { opacity: 1; -moz-transform: translateY(0px); }
	25% { opacity: 1; -moz-transform: translateY(0px); }
	30% { opacity: 0; -moz-transform: translateY(50px); }
	80% { opacity: 0; }
	100% { opacity: 0; }
}
@-webkit-keyframes topToBottom{
	0% { opacity: 0; }
	5% { opacity: 0; -webkit-transform: translateY(-50px); }
	10% { opacity: 1; -webkit-transform: translateY(0px); }
	25% { opacity: 1; -webkit-transform: translateY(0px); }
	30% { opacity: 0; -webkit-transform: translateY(50px); }
	80% { opacity: 0; }
	100% { opacity: 0; }
}
@-ms-keyframes topToBottom{
	0% { opacity: 0; }
	5% { opacity: 0; -ms-transform: translateY(-50px); }
	10% { opacity: 1; -ms-transform: translateY(0px); }
	25% { opacity: 1; -ms-transform: translateY(0px); }
	30% { opacity: 0; -ms-transform: translateY(50px); }
	80% { opacity: 0; }
	100% { opacity: 0; }
}
</style>

<div class="row">
  <div class="col-lg-8 col-lg-offset-2 text-center main">
    <img src="<?=$_base_dir?>/images/CloudEHRServer_white_72_square.png" />
    <h1>
    <div id="main_text_1">50% of your next</div>
    <div class="slidingVertical">
      <span>EHR</span>
      <span>EMR</span>
      <span>PHR</span>
      <span>App</span>
    </div>
    <div id="main_text_2">project</div>
    <br/>
    <div id="main_text_3">is already built.</div></h1>
    <h2 class="lead">Focus on features, deliver faster.
    EHRServer the open source clinical data repository,
    compliant with the openEHR standard. Now on the cloud.</h2>
    <p><a class="btn btn-lg btn-success" href="<?=$_base_dir?>/get_started" role="button">Get started now!</a></p>
  </div>
</div>
<!--
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 text-center main">
    <h1>EHRServer by <a href="http://www.cabolabs.com/" target="_blank">CaboLabs</a></h1>
    <h2 class="lead">50% of your next EHR project is already built</h2>
    <p><a class="btn btn-lg btn-success" href="get_started.html" role="button">Get started today</a></p>
  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <h1 class="text-center">The open source, service-oriented, clinical 
    data repository, compliant with the openEHR standard.</h1>
    <div class="space"></div>
  </div>
</div>
-->

<div class="row">
  <div class="col-lg-4">
    <h2>Generic clinical data repository</h2>
    <p>Store and organize any type of clinical record generated by any number of applications,
    and integrate everything in the unique Electronic Health Record of each patient.</p>
    <!--
    <p class="center v-air"><a class="btn btn-primary" href="#" role="button">Check some implementation scenarios &raquo;</a></p>
    -->
  </div>
  <div class="col-lg-4">
    <h2>Unique querying capabilities</h2>
    <p>Create data queries using the EHRServer Query Builder and make them instantly available
    from the EHRServer REST API, without writing a single line of code.</p>
    <!--
    <p class="center v-air"><a class="btn btn-primary" href="#" role="button">More about clinical data querying &raquo;</a></p>
    -->
 </div>
  <div class="col-lg-4">
    <h2>Powerful REST API</h2>
    <p>Hassle free clinical data storage and retrieval.
    Manage EHRs and access all the clinical information in a standardized way,
    from any system or application, when you need to.</p>
    <!--
    <p class="center v-air"><a class="btn btn-primary" href="#" role="button">Take a look at our REST API &raquo;</a></p>
    -->
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <h3>Why EHRServer?</h3>
    <p>EHRServer solves a very specific challenge all clinical information systems have to tackle:
    to build a clinical data repository.</p>
    <p>Clinical data is complex, heterogeneous and highly hierarchic.
    These characteristics make it very difficult to develop repositories that are:
    1. generic (can handle different types of data structures),
    2. maintainable in the long term,
    3. performant,
    4. scalable and
    5. integrable into different apps.</p>
    
    <p>At CaboLabs, it took us years of research and development, trial and error, to create a
    solution that complies with all of those requirements.</p>
    
    <p>The goal of the EHRServer is to save time and money to companies that are building their          
    EHR/EMR/PHR systems, and try to solve the same problem again and again, with custom solutions.</p>
    
    <p>With EHRServer your company can start working on apps right away, focusing on the
    value and features you will offer to your customers, reducing time to market, and avoiding
    time-wasting tasks related to solving complex problems that are already solved.</p>
   
    <p>Install your own self-managed instance
    of the EHRServer or use EHRServer Cloud. Even if you want to develop your own CDR backend
    later on, using EHRServer will help you create an MVP and test your idea without investing
    on building a backend.</p>
    
    
    <h4>Main features:</h4>
    <ol>
      <li>Web Console for simple management</li>
      <li>Full audit access for traceability</li>
      <li>Versioned clinical documents</li>
      <li>Service Oriented / REST API</li>
      <li>Supports XML and JSON formats</li>
      <li>Query Builder from the Web Console</li>
      <li>Supports any structure of clinical document</li>
      <li>Multitenant</li>
      <li>Open Source</li>
      <li>Compliant with the openEHR standard</li>
    </ol>
    
    <p class="center v-air"><a class="btn btn-primary" href="<?=$_base_dir?>/get_started" role="button">Get Started</a></p>
 </div>
  <div class="col-lg-6">
    <h3>How does it work?</h3>
    <p>The core of EHRServer is based on the openEHR specifications. Most of the capabilities
    and features offered by the EHRServer are because of this.</p>
    <p>The EHRServer should be fed with clinical
    document definitions called Operational Templates, or OPT for short. The OPTs define the
    semantics, data structures, constraints and terminology associated with each clinical document.
    It is basically an XML with metadata.</p>
    <p>When client apps commit clinical documents to the EHRServer,
    the data is indexed for querying. Of course, those documents should comply with their definitions (OPT).
    A manager will create data queries using the EHRServer Query Builder, and those queries are defined
    using only information from the OPTs, that is all clinical concepts like Blood Pressure, Diagnosis,
    Physical Examination, Glasgow Coma Scale, etc.</p>
    <p>To create queries there is no need of writing any SQL or source code.
    Once queries are saved, a client system can executed them using the REST API, pulling clincial data
    out from the EHRServer. That's it, data in, data out, all standardized,
    without writing a single line of code.</p>
    
    <h4>Simple as:</h4>
    <ol>
      <li>Create a clinical document definition</li>
      <li>Upload the definition to the EHRServer</li>
      <li>Create data queries based on document definitions</li>
      <li>Integrate the EHRServer API in your apps</li>
      <li>Commit some data</li>
      <li>Query and display your data</li>
    </ol>
    
    <p class="center v-air"><a class="btn btn-primary" href="<?=$_base_dir?>/learn" role="button">Continue learning</a></p>
    
  </div>
</div>

<!--
<div class="row">
  <div class="col-lg-4">
    <h2>Generic Clinical Data Repository that embraces change</h2>
    <p>Supports any type of clinical document, add new types of documents on the fly,
    without any downtime. Clinical document definitions are created by using freely
    available modeling tools and openEHR archetypes that represent atomic clinical content.</p>
    <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Compliant with the openEHR standard</h2>
    <p>The EHRServer is compliant with the openEHR specifications, enabling semantic
    interoperability, data sharing and analysis. This allows the EHRServer to be flexible (support any type of clinical data) and maintainable in the long term. openEHR offers a unique knowledge-based approach to clinical information specification and management that empowers clinical information systems and their users.</p>
    <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
 </div>
  <div class="col-lg-4">
    <h2>Fully auditable clinical document management</h2>
    <p>All the actions and transactions from the API and Web Console are logged. All
    the clinical documents on each patient's EHR are versioned (supports amendments and
    corrections without losing data). Managers can keep track of every change to an EHR
    from it's creation.</p>
    <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
  </div>
</div>
-->