<style type="text/css">

</style>

<div class="row">
  <div class="col-lg-8 col-lg-offset-2 text-center main">
    <img src="<?=$_base_dir?>/images/CloudEHRServer_white_72_square.png" />
    
    <h1>Clinical Data Management and Sharing Platform</h1>
      
    <h2 class="lead">Focus on features, deliver faster.
    EHRServer the open source clinical data repository,
    compliant with the openEHR standard. Now on the cloud.</h2>
    
    <p><a class="btn btn-lg btn-success" href="<?=$_base_dir?>/get_started" role="button">Get started now!</a></p>
  </div>
</div>
<!--
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 text-center main">
    <h1>EHRServer by <a href="http://www.cabolabs.com/" target="_blank">CaboLabs</a></h1>
    <h2 class="lead">50% of your next EHR project is already built</h2>
    <p><a class="btn btn-lg btn-success" href="get_started.html" role="button">Get started today</a></p>
  </div>
</div>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <h1 class="text-center">The open source, service-oriented, clinical 
    data repository, compliant with the openEHR standard.</h1>
    <div class="space"></div>
  </div>
</div>
-->

<div class="row">
  <div class="col-lg-4">
    <h2>Vendor Neutral Clinical Data Repository</h2>
    <p>Store and organize any type of clinical record generated by any number of applications,
    and integrate everything in the unique Electronic Health Record of each patient.</p>
    <!--
    <p class="center v-air"><a class="btn btn-primary" href="#" role="button">Check some implementation scenarios &raquo;</a></p>
    -->
  </div>
  <div class="col-lg-4">
    <h2>Unique querying capabilities</h2>
    <p>Create data queries using the EHRServer Query Builder and make them instantly available
    from the EHRServer REST API, without writing a single line of code.</p>
    <!--
    <p class="center v-air"><a class="btn btn-primary" href="#" role="button">More about clinical data querying &raquo;</a></p>
    -->
 </div>
  <div class="col-lg-4">
    <h2>Powerful REST API</h2>
    <p>Hassle free clinical data storage and retrieval.
    Manage EHRs and access all the clinical information in a standardized way,
    from any system or application, when you need to.</p>
    <!--
    <p class="center v-air"><a class="btn btn-primary" href="#" role="button">Take a look at our REST API &raquo;</a></p>
    -->
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h1>Why EHRServer?</h1>
    <p>
    EHRServer solves a very specific challenge all clinical information systems have to tackle:
    to build a clinical data repository. And companies are creating custom repositories for every
    new project, lacking resources on a problem that is already solved in a generic and standard way.
    </p>
    
    <p>
    Clinical data is complex, heterogeneous and highly hierarchic, making it very difficult to develop
    repositories that are:
      <ol>
        <li>generic (can handle different types of data structures)</li>
        <li>maintainable in the long term at low cost</li>
        <li>performant, secure and scalable</li>
        <li>integrable into different kinds of apps and platforms</li>
        <li>based on open technologies and standards (like the Internet)</li>
      </ol>
    </p>
    
    <p>It took us years of research and development, trial and error, to create a good solution
    for those requirements.</p>
    
    <p>The goal of the EHRServer is to save time and money to companies that are building their          
    EHR/EMR/PHR systems, and try to solve the same problem again and again, with custom solutions.</p>
    
    <p>With EHRServer your company can start working on apps right away, focusing on the
    value and features you will offer to your customers, reducing time to market, and avoiding
    time-wasting tasks related to solving complex problems that are already solved.</p>
   
    <p>Install your own self-managed instance or use EHRServer Cloud. Even if you want to develop
    your own CDR backend later on, using EHRServer will help you create an MVP and test your idea
    without investing on building a backend.</p>
    
    <p class="center v-air"><a class="btn btn-lg btn-primary" href="<?=$_base_dir?>/contact" role="button">Sounds interesting? Contact us</a></p>
  </div>
</div>

<a name="solution_partners"></a>
<div class="row">
  <div class="col-md-12">
    <h1>Solution Partners</h1>
    <p>We are not alone! We partner with top notch companies to offer a thorough solution.</p>  
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h2><a href="https://www.veratech.es/" target="_blank">VeraTech</a></h2>
    <p>Semantic interoperability and data quality for health</p>  
  </div>
  <div class="col-md-6">
    <h2><a href="https://www.glyms.com.ar/web/" target="_blank">GLYMS</a></h2>
    <p>Laboratory management solution</p>  
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h2><a href="https://www.nirdhost.com/" target="_blank">NIRD HOST</a></h2>
    <p>HIPAA compliant PaaS solution</p>  
  </div>
  <div class="col-md-6">
    <h2><a href="http://infoclinic.co/" target="_blank">InfoClinic</a></h2>
    <p>Health Terminology Server as a service</p>  
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h2><a href="http://www.vitalbox.com/" target="_blank">VitalBox</a></h2>
    <p>Interoperable Patient Portal solution</p>  
  </div>
  <div class="col-md-6">
    <h2><a href="http://www.miclinicaweb.com/" target="_blank">Cliniweb</a></h2>
    <p>EMR, finance and online appointments</p>  
  </div>
</div>
<!--
<div class="row">
  <div class="col-lg-4">
    <h2>Generic Clinical Data Repository that embraces change</h2>
    <p>Supports any type of clinical document, add new types of documents on the fly,
    without any downtime. Clinical document definitions are created by using freely
    available modeling tools and openEHR archetypes that represent atomic clinical content.</p>
    <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Compliant with the openEHR standard</h2>
    <p>The EHRServer is compliant with the openEHR specifications, enabling semantic
    interoperability, data sharing and analysis. This allows the EHRServer to be flexible (support any type of clinical data) and maintainable in the long term. openEHR offers a unique knowledge-based approach to clinical information specification and management that empowers clinical information systems and their users.</p>
    <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
 </div>
  <div class="col-lg-4">
    <h2>Fully auditable clinical document management</h2>
    <p>All the actions and transactions from the API and Web Console are logged. All
    the clinical documents on each patient's EHR are versioned (supports amendments and
    corrections without losing data). Managers can keep track of every change to an EHR
    from it's creation.</p>
    <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
  </div>
</div>
-->